import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
    //tutorialSidebar: [
    //    {
    //    type: 'autogenerated',
    //    dirName: '.'
    //    }
    //],
    docsSidebar: [
        {
            type: 'doc',
            id: 'documentation/intro',
            label: 'Úvod'
        },
        {
            type: 'doc',
            id: 'documentation/administration',
            label: 'Administrační rozhraní'
        },
        {
            type: 'doc',
            id: 'documentation/dashboard',
            label: 'Hlavní strana'
        },
        {
            type: 'category',
            label: 'Zásilky',
            items: [
                'documentation/packages/package-overview',                
                'documentation/packages/package-create',                
                'documentation/packages/package-detail',                               
                'documentation/packages/package-printing',                
            ],
        },
        {
            type: 'category',
            label: 'Objednávky',
            items: [
                'documentation/orders/order-overview',
                'documentation/orders/order-detail',
                'documentation/orders/order-create-printing',
                'documentation/orders/order-picking',
            ],
        },
        {
            type: 'category',
            label: 'Faktury',
            items: [
                'documentation/invoices/invoice-activate',
                'documentation/invoices/invoice-overview',
                'documentation/invoices/invoice-detail',
                'documentation/invoices/invoice-payment',
                'documentation/invoices/invoice-company',
                'documentation/invoices/invoice-bank-account',
                'documentation/invoices/invoice-number-series',
                'documentation/invoices/invoice-export',
            ],
        },
        {
            type: 'category',
            label: 'Nastavení',
            items: [
                {
                    type: 'category',
                    label: 'Adresy',
                    items: [
                        'documentation/settings/addresses/address-overview'
                    ],
                },
                {
                    type: 'category',
                    label: 'Aplikace',
                    items: [
                        'documentation/settings/application/application-overview',
                        //{
                        //    type: 'category',
                        //    label: 'Přidání aplikací',
                        //    items: [
                        //        //'documentation/settings/application/application-add/pohoda',
                        //        'documentation/settings/application/application-add/upgates',
                        //        // 'documentation/settings/application/application-add/shoptet.md',

                        //    ],
                        //},
                    ],
                },
                {
                    type: 'category',
                    label: 'Dopravci',
                    items: [
                        'documentation/settings/carriers/carrier-overview'
                        //{
                        //    type: 'category',
                        //    label: 'Aktivace dopravce',
                        //    items: [
                        //        'documentation/settings/carriers/activation/cp',
                        //        'documentation/settings/carriers/activation/dpd',
                        //        'documentation/settings/carriers/activation/geis',
                        //        'documentation/settings/carriers/activation/ppl'
                        //    ],
                        //},
                    ],
                },
                {
                    type: 'category',
                    label: 'Emaily',
                    items: [
                        'documentation/settings/emails/email-template',                     
                        'documentation/settings/emails/email-accounts'                     
                    ],
                },
                {
                    type: 'category',
                    label: 'Objednávky',
                    items: [
                        'documentation/settings/orders/order-settings',
                        'documentation/settings/orders/order-picking',
                        'documentation/settings/orders/order-payment',
                        'documentation/settings/orders/order-states'
                    ],
                },
                {
                    type: 'category',
                    label: 'Pravidla',
                    items: [
                        'documentation/settings/rules/rule-create',
                        'documentation/settings/rules/rule-overview',
                    ],
                },
                {
                    type: 'category',
                    label: 'Tiskárny',
                    items: [
                        'documentation/settings/printers/printer-overview',
                    ],
                },
                {
                    type: 'category',
                    label: 'Zásilky',
                    items: [
                        'documentation/settings/packages/package-settings',
                    ],
                },
                {
                    type: 'category',
                    label: 'Podpora',
                    items: [
                        'documentation/settings/support/basic-info',
                        'documentation/settings/support/discussion',
                    ],
                }
            ],
        },
        {
            type: 'category',
            label: 'Technické informace',
            items: [
                //'documentation/tech/intro',
                'documentation/tech/tracking',
            ],
        },
    ],
    apiSidebar: [
        {
            type: 'category',
            label: 'Základní informace',
            items: [
                'api/intro',
                'api/pripojeni-do-api',
                //{
                //    type: 'category',
                //    label: 'Typy klientů',
                //    items: [
                //        'api/clients/dotnet',
                //        'api/clients/php',                    
                //    ],
                //},
            ],
        },
    ],
    carrierSidebar: [
        {
            type: 'category',
            label: 'Základní informace',
            items: [
                'carrier/intro',
                {
                    type: 'category',
                    label: 'Seznam dopravců',
                    items: [
                        {
                            type: 'category',
                            label: 'CZ dopravci',
                            items: [
                                'carrier/cp',
                                'carrier/dpd',
                                'carrier/geis',
                                'carrier/gls',
                                'carrier/ppl',
                                'carrier/wedo',
                                'carrier/packeta',
                                'carrier/pickup',
                            ],
                        },
                        {
                            type: 'category',
                            label: 'SK dopravci',
                            items: [
                                'carrier/skdoprava',
                            ],
                        },
                    ],
                },
            ],
        },
    ],
    applicationSidebar: [
        {
            type: 'category',
            label: 'Základní informace',
            items: [
                'application/intro',
                {
                    type: 'category',
                    label: 'E-shop platformy',
                    items: [
                        'application/upgates',
                        'application/upgates-button',
                        'application/shoptet',
                    ],
                },
            ],
        },
    ],
    videoSidebar: [
        {
            type: 'doc',
            id: 'video/intro',
            label: 'Úvod'
        },
        {
            type: 'category',
            label: 'Dopravci',
            items: [
                'video/carriers/gls',
                'video/carriers/dpd',
                'video/carriers/wedo',
                'video/carriers/ppl',
                'video/carriers/zasilkovna',
                'video/carriers/cp',
            ],
        },
        {
            type: 'category',
            label: 'Nastavení',
            items: [
                {
                    type: 'category',
                    label: 'Adresy',
                    items: [
                        'video/settings/address/create'
                    ],
                },
                {
                    type: 'category',
                    label: 'Tiskárny',
                    items: [
                        'video/settings/print/create'
                    ],
                },
                {
                    type: 'category',
                    label: 'Objednávky',
                    items: [
                        'video/settings/order/status',
                        'video/settings/order/payment'
                    ],
                },
                {
                    type: 'category',
                    label: 'Pravidla',
                    items: [
                        'video/settings/rules/rule-for-status-change',
                    ],
                },
            ],
        },
        {
            type: 'category',
            label: 'Objednávky',
            items: [
                'video/orders/picking',
            ],
        },
    ]

};

export default sidebars;
