import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
    //tutorialSidebar: [
    //    {
    //    type: 'autogenerated',
    //    dirName: '.'
    //    }
    //],
    docsSidebar: [
        {
            type: 'doc',
            id: 'documentation/intro',
            label: 'Slovo úvodem'
        },
        {
            type: 'doc',
            id: 'documentation/administration',
            label: 'Administrační rozhraní'
        }
    ],
    apiSidebar: [
        {
            type: 'category',
            label: 'Základní informace',
            items: [
                'api/intro',
                'api/pripojeni-do-api',
                {
                    type: 'category',
                    label: 'Typy klientů',
                    items: [
                        'api/clients/net',
                        'api/clients/php',                    
                    ],
                },
            ],
        },
    ],
    carrierSidebar: [
        {
            type: 'category',
            label: 'Základní informace',
            items: [
                'carrier/intro',
                {
                    type: 'category',
                    label: 'Typy dopravců',
                    items: [
                        {
                            type: 'category',
                            label: 'CZ dopravci',
                            items: [
                                'carrier/dpd',
                                'carrier/ppl',
                            ],
                        },
                        {
                            type: 'category',
                            label: 'SK dopravci',
                            items: [
                                'carrier/skdoprava',
                            ],
                        },
                    ],
                },
            ],
        },
    ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
